name: Dev Stats

on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:
jobs:
  DevStats:
    name: "Update Stats"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          repository: 'nick22985/Dev-Stats'
      - run: npm ci
      - run: npm run start --if-present
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          EXCLUDE_PROJECT: ${{ secrets.EXCLUDE_PROJECT }}
          SHOW_SHORT_INFO: "true"
          SHOW_COMITS: "true"
          SHOW_DAY_OF_WEEK: "true"
          SHOW_BREAK_DOWN: "true"
          SHOW_TIMEZONE: "true"
          SHOW_EDITORS: "true"
          SHOW_LANGUAGES: "true"
          SHOW_OS: "true"
          SHOW_HOSTS: "true"
          SHOW_LANGUAGE_PER_REPO: "true"
          SHOW_PROJECTS: "true"
          EXLUDE_PROJECT_NAME: "[Redacted]"
